services:
  - type: web
    name: biascheck-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bias_api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface
